                                            #   Airport Project Version 1.0
                                            #   Configuration f !
sch_list = [
            "LO Austria",
            "EB Belgium",
            "LK Czech Republic",
            "LC Cyprus",
            "EK Denmark",
            "EE Estonia",
            "EF Finland",
            "LF France",
            "ED Germany",
            "LG Greece",
            "EH Netherlands",
            "LH Hungary",
            "BI Iceland",
            "LI Italy",
            "EV Latvia",
            "EY Lithuania",
            "EL Luxembourg",
            "LM Malta",
            "EN Norway",
            "EP Poland",
            "LP Portugal",
            "LZ Slovakia",
            "LJ Slovenia",
            "LE Spain",
            "ES Sweden",
            "LS Switzerland",
        ]